version: "3.8"

volumes:
  pgdata:
  minio_data:

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env                 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env                     
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   
      - "9001:9001"   

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}  # for prisma generate at build-time
    env_file:
      - .env                         # loads DATABASE_URL, MINIO_*, etc.
    environment:
      REDIS_URL: ${REDIS_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      S3_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "3001:3001"
      - "5555:5555"   # Prisma Studio
    depends_on:
      - postgres
      - redis
      - minio
    entrypoint:
      - sh
      - -c
      - |
        npx prisma migrate deploy && \
        npx prisma generate && \
        node dist/main.js

  worker:
    build:
      context: ./apps/worker
      dockerfile: Dockerfile
      args:
        REDIS_URL: ${REDIS_URL}
        API_URL: ${BACKEND_URL}
    env_file:
      - .env                        
    environment:
      REDIS_URL: ${REDIS_URL}
      API_URL: ${BACKEND_URL}
      S3_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "8001:8001"
    depends_on:
      - backend
      - redis
      - minio

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    env_file:
      - .env                        
    environment:
      VITE_API_URL: ${BACKEND_URL}
      VITE_WS_URL: ${WS_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend